global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'ba-inspection'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
